name: Angular CI & Deploy

on:
  push:
    branches:
      - main

# Allow this workflow to write to the gh-pages branch
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the app with the correct base href for GitHub Pages
      - name: Build Angular app
        run: npx ng build --configuration=production --base-href="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"

      # Deploy the built folder to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/ecommerce-frontend/browser
